export const websiteContent = {
  es: {
    navLabel: 'Navegación principal', homeLabel: 'Rive Intelligente by Innova Montreal', languageLabel: 'Idioma',
    navMethod: 'Método', navApplications: 'Opciones', navQuestions: 'Preguntas', call: 'Evaluar mi proyecto',
    eyebrow: 'Sitios modulares · IA integrable', heroFirst: 'Tu web puede ser', heroSecond: 'el sistema de tu crecimiento.',
    heroLead: 'Creamos sitios web preparados para incorporar chatbot, CRM propio, tienda online, pagos y túneles de venta, sin obligarte a comprar una plataforma de IA.',
    request: 'Evaluar mi proyecto', how: 'Explorar las opciones', proofLabel: 'Características del servicio',
    proof: [['Modular', 'activa solo lo necesario'], ['CRM propio', 'contactos y seguimiento'], ['Sin licencia IA', 'como requisito de entrada']],
    visualLabel: 'Vista previa de un ecosistema web inteligente', roadmap: 'Arquitectura modular', planTitle: 'Ecosistema web', ongoing: 'Evolutivo', teamProgress: 'Base lista para integrar',
    planSteps: [
      ['Sitio web', 'Rápido, claro y orientado a conversión', 'Base'],
      ['CRM + túnel', 'Captura, seguimiento y automatización', 'Opción'],
      ['Chatbot + comercio', 'Activados cuando aporten valor', 'Opción'],
    ],
    pilotGoal: 'Principio de diseño', hours: 'Empezar útil', freed: 'y ampliar con criterio', opportunities: '5 módulos', ready: 'combinables según el proyecto', supported: 'Compatible con Bluehost', operations: 'capacidad validada al definir el alcance',
    signalLabel: 'Arquitectura del servicio', intent: 'De vitrina a sistema comercial', strategy: 'Web', processes: 'CRM', people: 'Automatización', purpose: 'Crecimiento medible',
    challengeKicker: 'El problema habitual', challengeTitle: 'Tu sitio no debería terminar como un folleto.',
    challengeIntro: 'Muchas empresas pagan por una web que se ve bien, pero no conversa con los visitantes, no organiza los prospectos y no acompaña la venta.',
    frictions: [
      ['Herramientas desconectadas', 'Formularios, correos, contactos y ventas viven en sistemas distintos.'],
      ['Prospectos sin seguimiento', 'Las oportunidades llegan, pero no existe un proceso claro para convertirlas.'],
      ['Tecnología sobredimensionada', 'Se compran soluciones costosas antes de confirmar qué necesita realmente el negocio.'],
    ],
    bridgeStrong: 'Construimos la base antes de añadir complejidad.', bridgeRest: 'Cada módulo responde a una necesidad comercial concreta y puede activarse cuando el negocio esté preparado.',
    methodKicker: 'La creación', methodTitleOne: 'Una base sólida.', methodTitleTwo: 'Opciones que evolucionan.', methodIntro: 'Tres etapas para lanzar una primera versión útil y dejarla preparada para integrar nuevas capacidades.',
    methods: [
      { stage: 'Definir', title: 'Arquitectura y conversión', copy: 'Aclaramos la oferta, el público, las acciones esperadas y los datos que el sitio deberá gestionar.', bullets: ['Mapa del recorrido', 'Contenido prioritario', 'Plan de módulos'] },
      { stage: 'Crear', title: 'Sitio rápido y adaptable', copy: 'Diseñamos una experiencia multilingüe, accesible y optimizada para móvil, búsqueda y campañas.', bullets: ['Diseño a medida', 'Rendimiento y SEO', 'Analítica preparada'] },
      { stage: 'Conectar', title: 'Automatización útil', copy: 'Integramos CRM, chatbot, pagos o comercio solamente cuando apoyen un proceso real.', bullets: ['Captura de prospectos', 'Seguimiento comercial', 'Integraciones por etapas'] },
    ],
    applicationsKicker: 'Módulos opcionales', applicationsTitle: 'Elige lo que tu negocio necesita ahora.', applicationsIntro: 'El sitio funciona desde su primera versión y queda preparado para incorporar más capacidades sin rehacerlo desde cero.',
    useCases: [
      { number: '01', area: 'Conversación', title: 'Chatbot conectado a tu negocio.', copy: 'Responde preguntas, orienta al visitante y deriva las conversaciones importantes a una persona.', tags: ['Chatbot', 'FAQ', 'Derivación'] },
      { number: '02', area: 'Ventas', title: 'CRM y túnel en el mismo recorrido.', copy: 'Captura la fuente de cada prospecto, organiza el seguimiento y mide qué campañas generan citas.', tags: ['CRM', 'UTM', 'Automatización'] },
      { number: '03', area: 'Comercio', title: 'Tienda y pagos cuando haga sentido.', copy: 'Añade catálogo, pedidos y pagos mediante proveedores compatibles, después de validar operación y alojamiento.', tags: ['Tienda', 'Stripe / PayPal', 'Pedidos'] },
    ],
    outcomesKicker: 'La diferencia', outcomesOne: 'Un solo sitio.', outcomesTwo: 'Varios motores de crecimiento.', outcomesCopy: 'La web deja de ser un gasto aislado y se convierte en una infraestructura comercial que captura, organiza y acompaña oportunidades.', outcomesCta: 'Definir mi primera versión',
    metrics: { recovered: 'Punto de partida', hours: 'Web', perWeek: 'rápida, clara y lista para convertir', speed: 'Captación', cycle: 'formularios y citas', quality: 'Seguimiento', consistency: 'CRM y automatización', adoption: 'Asistencia', activeUse: 'chatbot opcional', trust: 'Comercio', safeUse: 'tienda y pagos opcionales' },
    diagnosisKicker: 'Primera etapa', diagnosisTitle: 'Construyamos la versión correcta.', diagnosisCopy: 'Cuéntanos qué debe lograr tu sitio. En una conversación de 30 minutos definiremos la base, los módulos prioritarios y el siguiente paso.',
    promises: [['30 minutos', 'para entender el proyecto'], ['Una arquitectura', 'adaptada a tus objetivos'], ['Sin obligación', 'de comprar una solución de IA']], sourceDetected: 'Fuente de campaña detectada:',
    successLabel: 'Consulta solicitada', successTitle: 'Gracias. Guardamos tu horario preferido.', successCopy: 'Te escribiremos para confirmar la fecha y preparar la conversación sobre tu sitio.', sendAnother: 'Enviar otra respuesta',
    formLabel: 'Evaluación del proyecto', formTitle: 'Cuéntanos sobre tu sitio', name: 'Nombre', namePlaceholder: 'Tu nombre', company: 'Empresa', companyPlaceholder: 'Nombre de la empresa', email: 'Email corporativo', emailPlaceholder: 'nombre@empresa.com', teamSize: 'Tamaño del equipo', select: 'Selecciona una opción', sizes: ['1–10 personas', '11–50 personas', '51–200 personas', 'Más de 200 personas'], challenge: '¿Qué debería lograr tu nuevo sitio?', challengePlaceholder: 'Por ejemplo: generar citas, organizar prospectos, vender en línea o responder preguntas…', appointmentKicker: 'Elige tu preferencia', appointmentDate: 'Fecha preferida', appointmentTime: 'Hora preferida', appointmentTimezone: 'Hora de Montreal · La cita se confirma por correo', formSubmit: 'Evaluar mi proyecto', demoNote: 'Los datos se guardan en nuestro CRM únicamente para gestionar tu solicitud y confirmar la cita.',
    sending: 'Enviando…', consent: 'Acepto que Rive Intelligente almacene estos datos para responder a mi solicitud.', formError: 'No pudimos registrar la solicitud. Revisa tu conexión e inténtalo de nuevo.', formUnavailable: 'El formulario se está terminando de configurar. Inténtalo de nuevo más tarde.',
    faqKicker: 'Preguntas frecuentes', faqTitle: 'Antes de iniciar el proyecto.', faqs: [
      ['¿Necesito comprar una plataforma de IA?', 'No. El sitio se crea primero como una base útil y modular. Si un chatbot u otra función de IA aporta valor, se integra con el proveedor y el alcance adecuados.'],
      ['¿Mi alojamiento permite una tienda online?', 'El alojamiento actual dispone de SSL, bases de datos, PHP y herramientas de instalación compatibles con una solución de comercio. La configuración final se valida según catálogo, tráfico y operación.'],
      ['¿Se pueden aceptar pagos?', 'Sí, mediante proveedores compatibles como Stripe o PayPal. La cuenta comercial, la aprobación del proveedor y sus comisiones son independientes del alojamiento.'],
      ['¿El CRM también puede ser propio?', 'Sí. Podemos crear un CRM ligero adaptado al proceso comercial o conectar el sitio con una herramienta que la empresa ya utilice.'],
    ],
    footerLineOne: 'Tu sitio web,', footerLineTwo: 'preparado para lo que sigue.', footerCta: 'Hablemos', footerDescriptor: 'Sitios web preparados para integrar IA', backTop: 'Volver arriba ↑',
  },
  en: {
    navLabel: 'Main navigation', homeLabel: 'Rive Intelligente by Innova Montreal', languageLabel: 'Language',
    navMethod: 'Method', navApplications: 'Options', navQuestions: 'Questions', call: 'Assess my project',
    eyebrow: 'Modular websites · AI-ready', heroFirst: 'Your website can become', heroSecond: 'your growth system.',
    heroLead: 'We build websites ready to add a chatbot, your own CRM, online store, payments and sales funnels—without forcing you to buy an AI platform.',
    request: 'Assess my project', how: 'Explore the options', proofLabel: 'Service highlights',
    proof: [['Modular', 'activate only what you need'], ['Your own CRM', 'contacts and follow-up'], ['No AI licence', 'required to get started']],
    visualLabel: 'Smart web ecosystem preview', roadmap: 'Modular architecture', planTitle: 'Web ecosystem', ongoing: 'Scalable', teamProgress: 'Foundation ready to integrate',
    planSteps: [
      ['Website', 'Fast, clear and built to convert', 'Core'],
      ['CRM + funnel', 'Capture, follow-up and automation', 'Option'],
      ['Chatbot + commerce', 'Activated when they add value', 'Option'],
    ],
    pilotGoal: 'Design principle', hours: 'Start useful', freed: 'then expand with purpose', opportunities: '5 modules', ready: 'combined around your project', supported: 'Bluehost compatible', operations: 'capacity checked during scoping',
    signalLabel: 'Service architecture', intent: 'From brochure to sales system', strategy: 'Website', processes: 'CRM', people: 'Automation', purpose: 'Measurable growth',
    challengeKicker: 'The common problem', challengeTitle: 'Your website should not end up as a brochure.',
    challengeIntro: 'Many companies pay for a site that looks good but does not engage visitors, organize leads or support the sales process.',
    frictions: [
      ['Disconnected tools', 'Forms, emails, contacts and sales activity live in separate systems.'],
      ['Leads without follow-up', 'Opportunities arrive, but there is no clear process for turning them into customers.'],
      ['Oversized technology', 'Expensive solutions are purchased before the business confirms what it actually needs.'],
    ],
    bridgeStrong: 'We build the foundation before adding complexity.', bridgeRest: 'Every module answers a concrete business need and can be activated when the company is ready.',
    methodKicker: 'The build', methodTitleOne: 'A solid foundation.', methodTitleTwo: 'Options that evolve.', methodIntro: 'Three stages to launch a useful first version and keep it ready for new capabilities.',
    methods: [
      { stage: 'Define', title: 'Architecture and conversion', copy: 'We clarify the offer, audience, desired actions and information the website needs to manage.', bullets: ['Customer journey', 'Priority content', 'Module roadmap'] },
      { stage: 'Build', title: 'Fast, adaptable website', copy: 'We design a multilingual, accessible experience optimized for mobile, search and campaigns.', bullets: ['Custom design', 'Performance and SEO', 'Analytics ready'] },
      { stage: 'Connect', title: 'Useful automation', copy: 'We integrate CRM, chatbot, payments or commerce only when they support a real process.', bullets: ['Lead capture', 'Sales follow-up', 'Phased integrations'] },
    ],
    applicationsKicker: 'Optional modules', applicationsTitle: 'Choose what the business needs now.', applicationsIntro: 'The site works from its first release and remains ready to add capabilities without rebuilding from scratch.',
    useCases: [
      { number: '01', area: 'Conversation', title: 'A chatbot connected to your business.', copy: 'Answer questions, guide visitors and hand important conversations to a person.', tags: ['Chatbot', 'FAQ', 'Handoff'] },
      { number: '02', area: 'Sales', title: 'CRM and funnel in one journey.', copy: 'Capture every lead source, organize follow-up and measure which campaigns generate appointments.', tags: ['CRM', 'UTM', 'Automation'] },
      { number: '03', area: 'Commerce', title: 'Store and payments when they make sense.', copy: 'Add products, orders and payments through compatible providers after validating operations and hosting.', tags: ['Store', 'Stripe / PayPal', 'Orders'] },
    ],
    outcomesKicker: 'The difference', outcomesOne: 'One website.', outcomesTwo: 'Several growth engines.', outcomesCopy: 'Your website stops being an isolated expense and becomes commercial infrastructure that captures, organizes and develops opportunities.', outcomesCta: 'Define my first release',
    metrics: { recovered: 'Starting point', hours: 'Web', perWeek: 'fast, clear and ready to convert', speed: 'Acquisition', cycle: 'forms and appointments', quality: 'Follow-up', consistency: 'CRM and automation', adoption: 'Assistance', activeUse: 'optional chatbot', trust: 'Commerce', safeUse: 'optional store and payments' },
    diagnosisKicker: 'First stage', diagnosisTitle: 'Let’s build the right first version.', diagnosisCopy: 'Tell us what your website should achieve. In a 30-minute conversation, we will define the foundation, priority modules and next step.',
    promises: [['30 minutes', 'to understand the project'], ['One architecture', 'built around your goals'], ['No obligation', 'to purchase an AI solution']], sourceDetected: 'Campaign source detected:',
    successLabel: 'Consultation requested', successTitle: 'Thank you. We saved your preferred time.', successCopy: 'We will email you to confirm the date and prepare the conversation about your website.', sendAnother: 'Send another response',
    formLabel: 'Project assessment', formTitle: 'Tell us about your website', name: 'Name', namePlaceholder: 'Your name', company: 'Company', companyPlaceholder: 'Company name', email: 'Work email', emailPlaceholder: 'name@company.com', teamSize: 'Team size', select: 'Select an option', sizes: ['1–10 people', '11–50 people', '51–200 people', 'More than 200 people'], challenge: 'What should your new website achieve?', challengePlaceholder: 'For example: generate appointments, organize leads, sell online or answer questions…', appointmentKicker: 'Choose your preference', appointmentDate: 'Preferred date', appointmentTime: 'Preferred time', appointmentTimezone: 'Montreal time · Appointment confirmed by email', formSubmit: 'Assess my project', demoNote: 'Your data is stored in our CRM only to manage your request and confirm the appointment.',
    sending: 'Sending…', consent: 'I agree that Rive Intelligente may store this information to respond to my request.', formError: 'We could not record your request. Check your connection and try again.', formUnavailable: 'The form is still being configured. Please try again later.',
    faqKicker: 'Frequently asked questions', faqTitle: 'Before starting the project.', faqs: [
      ['Do I need to buy an AI platform?', 'No. The website is first built as a useful, modular foundation. If a chatbot or another AI capability adds value, we integrate the appropriate provider and scope.'],
      ['Can my hosting support an online store?', 'The current hosting provides SSL, databases, PHP and installation tools compatible with a commerce solution. Final configuration is validated against the catalogue, traffic and operations.'],
      ['Can the website accept payments?', 'Yes, through compatible providers such as Stripe or PayPal. Merchant approval, the payment account and transaction fees are separate from hosting.'],
      ['Can the CRM belong to us?', 'Yes. We can create a lightweight CRM around your sales process or connect the website to a system the company already uses.'],
    ],
    footerLineOne: 'Your website,', footerLineTwo: 'ready for what comes next.', footerCta: 'Let’s talk', footerDescriptor: 'Websites ready for AI integration', backTop: 'Back to top ↑',
  },
  fr: {
    navLabel: 'Navigation principale', homeLabel: 'Rive Intelligente by Innova Montreal', languageLabel: 'Langue',
    navMethod: 'Méthode', navApplications: 'Options', navQuestions: 'Questions', call: 'Évaluer mon projet',
    eyebrow: 'Sites modulaires · IA intégrable', heroFirst: 'Votre site peut devenir', heroSecond: 'le système de votre croissance.',
    heroLead: 'Nous créons des sites prêts à intégrer un chatbot, votre propre CRM, une boutique en ligne, des paiements et des tunnels de vente, sans vous obliger à acheter une plateforme d’IA.',
    request: 'Évaluer mon projet', how: 'Explorer les options', proofLabel: 'Points forts du service',
    proof: [['Modulaire', 'activez seulement l’utile'], ['Votre CRM', 'contacts et suivi'], ['Sans licence IA', 'obligatoire au départ']],
    visualLabel: 'Aperçu d’un écosystème web intelligent', roadmap: 'Architecture modulaire', planTitle: 'Écosystème web', ongoing: 'Évolutif', teamProgress: 'Base prête à intégrer',
    planSteps: [
      ['Site web', 'Rapide, clair et orienté conversion', 'Base'],
      ['CRM + tunnel', 'Collecte, suivi et automatisation', 'Option'],
      ['Chatbot + commerce', 'Activés lorsqu’ils créent de la valeur', 'Option'],
    ],
    pilotGoal: 'Principe de conception', hours: 'Commencer utile', freed: 'puis évoluer avec méthode', opportunities: '5 modules', ready: 'combinés selon votre projet', supported: 'Compatible Bluehost', operations: 'capacité vérifiée au cadrage',
    signalLabel: 'Architecture du service', intent: 'De vitrine à système commercial', strategy: 'Site', processes: 'CRM', people: 'Automatisation', purpose: 'Croissance mesurable',
    challengeKicker: 'Le problème courant', challengeTitle: 'Votre site ne devrait pas finir comme une brochure.',
    challengeIntro: 'Beaucoup d’entreprises paient pour un site attrayant qui ne dialogue pas avec les visiteurs, n’organise pas les prospects et n’accompagne pas la vente.',
    frictions: [
      ['Des outils déconnectés', 'Formulaires, courriels, contacts et ventes vivent dans des systèmes séparés.'],
      ['Des prospects sans suivi', 'Les occasions arrivent, mais aucun processus clair ne les accompagne vers la vente.'],
      ['Une technologie surdimensionnée', 'Des solutions coûteuses sont achetées avant de confirmer les besoins réels de l’entreprise.'],
    ],
    bridgeStrong: 'Nous construisons la base avant d’ajouter la complexité.', bridgeRest: 'Chaque module répond à un besoin commercial concret et peut être activé lorsque l’entreprise est prête.',
    methodKicker: 'La création', methodTitleOne: 'Une base solide.', methodTitleTwo: 'Des options qui évoluent.', methodIntro: 'Trois étapes pour lancer une première version utile et la préparer à accueillir de nouvelles capacités.',
    methods: [
      { stage: 'Définir', title: 'Architecture et conversion', copy: 'Nous clarifions l’offre, le public, les actions attendues et les renseignements que le site doit gérer.', bullets: ['Parcours client', 'Contenu prioritaire', 'Plan des modules'] },
      { stage: 'Créer', title: 'Site rapide et adaptable', copy: 'Nous concevons une expérience multilingue, accessible et optimisée pour le mobile, la recherche et les campagnes.', bullets: ['Design sur mesure', 'Performance et SEO', 'Analytique préparée'] },
      { stage: 'Connecter', title: 'Automatisation utile', copy: 'Nous intégrons CRM, chatbot, paiements ou commerce seulement lorsqu’ils soutiennent un processus réel.', bullets: ['Collecte de prospects', 'Suivi commercial', 'Intégrations par étapes'] },
    ],
    applicationsKicker: 'Modules optionnels', applicationsTitle: 'Choisissez ce qui est utile maintenant.', applicationsIntro: 'Le site fonctionne dès sa première version et reste prêt à évoluer sans devoir être reconstruit.',
    useCases: [
      { number: '01', area: 'Conversation', title: 'Un chatbot relié à votre entreprise.', copy: 'Répondez aux questions, guidez les visiteurs et transmettez les échanges importants à une personne.', tags: ['Chatbot', 'FAQ', 'Transfert'] },
      { number: '02', area: 'Ventes', title: 'CRM et tunnel dans un même parcours.', copy: 'Identifiez la source de chaque prospect, organisez le suivi et mesurez les campagnes qui génèrent des rendez-vous.', tags: ['CRM', 'UTM', 'Automatisation'] },
      { number: '03', area: 'Commerce', title: 'Boutique et paiements au bon moment.', copy: 'Ajoutez catalogue, commandes et paiements avec des fournisseurs compatibles après validation des opérations et de l’hébergement.', tags: ['Boutique', 'Stripe / PayPal', 'Commandes'] },
    ],
    outcomesKicker: 'La différence', outcomesOne: 'Un seul site.', outcomesTwo: 'Plusieurs moteurs de croissance.', outcomesCopy: 'Votre site cesse d’être une dépense isolée et devient une infrastructure commerciale qui collecte, organise et développe les occasions.', outcomesCta: 'Définir ma première version',
    metrics: { recovered: 'Point de départ', hours: 'Web', perWeek: 'rapide, clair et prêt à convertir', speed: 'Acquisition', cycle: 'formulaires et rendez-vous', quality: 'Suivi', consistency: 'CRM et automatisation', adoption: 'Assistance', activeUse: 'chatbot optionnel', trust: 'Commerce', safeUse: 'boutique et paiements optionnels' },
    diagnosisKicker: 'Première étape', diagnosisTitle: 'Construisons la bonne première version.', diagnosisCopy: 'Dites-nous ce que votre site doit accomplir. En 30 minutes, nous définirons la base, les modules prioritaires et la prochaine étape.',
    promises: [['30 minutes', 'pour comprendre le projet'], ['Une architecture', 'adaptée à vos objectifs'], ['Sans obligation', 'd’acheter une solution d’IA']], sourceDetected: 'Source de campagne détectée :',
    successLabel: 'Consultation demandée', successTitle: 'Merci. Votre préférence est enregistrée.', successCopy: 'Nous vous écrirons pour confirmer la date et préparer l’échange sur votre site.', sendAnother: 'Envoyer une autre réponse',
    formLabel: 'Évaluation du projet', formTitle: 'Parlez-nous de votre site', name: 'Nom', namePlaceholder: 'Votre nom', company: 'Entreprise', companyPlaceholder: 'Nom de l’entreprise', email: 'Courriel professionnel', emailPlaceholder: 'nom@entreprise.com', teamSize: 'Taille de l’équipe', select: 'Sélectionnez une option', sizes: ['1–10 personnes', '11–50 personnes', '51–200 personnes', 'Plus de 200 personnes'], challenge: 'Que doit accomplir votre nouveau site ?', challengePlaceholder: 'Par exemple : générer des rendez-vous, organiser les prospects, vendre en ligne ou répondre aux questions…', appointmentKicker: 'Choisissez votre préférence', appointmentDate: 'Date souhaitée', appointmentTime: 'Heure souhaitée', appointmentTimezone: 'Heure de Montréal · Rendez-vous confirmé par courriel', formSubmit: 'Évaluer mon projet', demoNote: 'Vos données sont conservées dans notre CRM uniquement pour gérer votre demande et confirmer le rendez-vous.',
    sending: 'Envoi…', consent: 'J’accepte que Rive Intelligente conserve ces renseignements afin de répondre à ma demande.', formError: 'Nous n’avons pas pu enregistrer la demande. Vérifiez votre connexion et réessayez.', formUnavailable: 'Le formulaire est en cours de configuration. Veuillez réessayer plus tard.',
    faqKicker: 'Questions fréquentes', faqTitle: 'Avant de lancer le projet.', faqs: [
      ['Dois-je acheter une plateforme d’IA ?', 'Non. Le site est d’abord conçu comme une base utile et modulaire. Si un chatbot ou une autre fonction d’IA crée de la valeur, nous intégrons le fournisseur et la portée appropriés.'],
      ['Mon hébergement permet-il une boutique en ligne ?', 'L’hébergement actuel offre SSL, bases de données, PHP et outils d’installation compatibles avec une solution de commerce. La configuration finale dépend du catalogue, du trafic et des opérations.'],
      ['Le site peut-il accepter des paiements ?', 'Oui, avec des fournisseurs compatibles comme Stripe ou PayPal. Le compte marchand, l’approbation du fournisseur et les frais de transaction restent indépendants de l’hébergement.'],
      ['Le CRM peut-il nous appartenir ?', 'Oui. Nous pouvons créer un CRM léger adapté à votre processus commercial ou connecter le site à un système déjà utilisé par l’entreprise.'],
    ],
    footerLineOne: 'Votre site web,', footerLineTwo: 'prêt pour la prochaine étape.', footerCta: 'Échangeons', footerDescriptor: 'Sites web prêts à intégrer l’IA', backTop: 'Retour en haut ↑',
  },
} as const;
